sonar.projectKey=tjabane_agent-krabs
sonar.organization=tjabane

sonar.sources=src
sonar.tests=tests/krabs_unit_tests,tests/krabs_integration_tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
