sonar.projectKey=tjabane_agent-julius
sonar.organization=tjabane

sonar.sources=src
sonar.tests=tests/julius_unit_tests,tests/julius_integration_tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
