from krabs_services.communication.email_service import AzureEmailService as AzureEmailService
from krabs_services.communication.twilio_client import TwilioClient as TwilioClient
from krabs_services.finance.investec_client import InvestecClient as InvestecClient
